-- MySQL Script generated by MySQL Workbench
-- Fri May 12 20:02:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pt_data
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pt_data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pt_data` DEFAULT CHARACTER SET utf8 ;
USE `pt_data` ;

-- -----------------------------------------------------
-- Table `pt_data`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pt_data`.`estudiante` (
  `id_estudiante` VARCHAR(20) NOT NULL,
  `id_tutor` VARCHAR(20) NOT NULL,
  `carrera` VARCHAR(64) NOT NULL,
  `cantidad_de_reportes` INT NOT NULL,
  `horas_acumuladas` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_estudiante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pt_data`.`reportes_semanales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pt_data`.`reportes_semanales` (
  `id_reporte` INT NOT NULL AUTO_INCREMENT,
  `id_estudiante` VARCHAR(20) NOT NULL,
  `id_tutor` VARCHAR(20) NOT NULL,
  `numero_reporte` INT NOT NULL,
  `horas_reporte` DECIMAL(10,2) NOT NULL,
  `aprobacion_tutor` VARCHAR(32) NOT NULL,
  `aprobacion_coordinador` VARCHAR(32) NOT NULL,
  `resumen_domingo` VARCHAR(512) NULL,
  `resumen_lunes` VARCHAR(512) NULL,
  `resumen_martes` VARCHAR(512) NULL,
  `resumen_miercoles` VARCHAR(512) NULL,
  `resumen_jueves` VARCHAR(512) NULL,
  `resumen_viernes` VARCHAR(512) NULL,
  PRIMARY KEY (`id_reporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pt_data`.`tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pt_data`.`tutor` (
  `id_tutor` VARCHAR(20) NOT NULL,
  `id_estudiante` VARCHAR(20) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pt_data`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pt_data`.`usuario` (
  `cedula` VARCHAR(20) NOT NULL,
  `nombre_1` VARCHAR(32) NOT NULL,
  `nombre_2` VARCHAR(32) NOT NULL,
  `apellido_p` VARCHAR(32) NOT NULL,
  `apellido_m` VARCHAR(32) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasena` CHAR(105) NOT NULL,
  `tipo_de_usuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
